formats = "ipynb,py:percent"

notebook_mapping = [
  ["notebooks/config_manager.ipynb",    "src/config_manager.py"],
  ["notebooks/joplinai.ipynb",          "joplinai.py"],
  ["notebooks/queryanswer.ipynb",       "src/queryanswer.py"],
  ["notebooks/joplin_qa_api.ipynb",     "joplin_qa_api.py"],
  ["notebooks/joplin_web_app.ipynb",    "joplin_web_app.py"],
  ["notebooks/user_manager.ipynb",      "src/user_manager.py"],
]
